### ISSUE TITLE
4.0.0 not reading svgtofont config in package.json

### ISSUE THREAD

**Issue by benwharg** [jaywcjlove/svgtofont#212] opened 2023-10-07 01:39 UTC
Have this in my package.json (also tried similar in .svgtofontrc but no luck)
```
"scripts": {
 ...
 "font": "svgtofont"
},
 "svgtofont": {
    "fontName": "name",
    "css": true,
    "log": true,
    "classNamePrefix": "pf",
    "outSVGReact": false,
    "src": "path/to/src",
    "dist": " path/to/dest",
    "website": false
 },
```

Can't get it to pick up the config. Any ideas what I'm doing wrong? thanks

**Comment by jaywcjlove** [comment] 2023-10-07 02:21
@benwharg If a `.svgtofontrc` configuration exists, the configuration in package.json will be invalid.

**Comment by benwharg** [comment] 2023-10-07 02:22
hey thanks for the reply! i did remove the .svgtofontrc before trying in package.json

**Comment by jaywcjlove** [comment] 2023-10-07 02:24
@benwharg I'm not sure how you added the configuration, I just tested it and it's valid in package.json.

**Comment by benwharg** [comment] 2023-10-07 02:25
does it have to be anywhere in particular in package.json? is my npm run svgtofont script ok? sorry, i am new to this package. but i really enjoy it!

**Comment by jaywcjlove** [comment] 2023-10-07 02:33
<img width="1337" alt="image" src="https://github.com/jaywcjlove/svgtofont/assets/1680273/83c75fe5-38e9-4061-89bd-618986922c0d">


@benwharg  I can't help you, I can't reproduce your error

**Comment by benwharg** [comment] 2023-10-07 02:36
is there any difference between what i am doing? your npm run example is using node on your test.js file, i am basically running `npx svgtofont`

**Comment by benwharg** [comment] 2023-10-07 02:42
i see my issue, in `cli.ts` the options are hardcoded

<img width="641" alt="image" src="https://github.com/jaywcjlove/svgtofont/assets/18319205/fecb91f1-1262-46ee-b41d-b8e4d2997909">

i will likely need to make my own js file and run with node like in your example. thank you for talking with me! i will go try.

**Closed** 2023-10-08 01:42 UTC
